### ISSUE TITLE
bogus adb output kills at int pid = System.Convert.ToInt32(pid_token);

### ISSUE THREAD

**Issue by 40th** [lancelot-coder-chen/logcat-toolwindow-vsext#1]
Oneplus3 sends output like the following

`// getting junk like this from 1+3
// 06-03 14:34:39.128 E/%s l.%d (%s): ( 4024): vendor/qcom/proprietary/securemsm-noship/Qmp/libsphinxcore/qmp_sphinx_bex/qmp_sphinx_feature_interpreter/qmp_sphinx_feature_interpreter.c

System.FormatException occurred
  HResult=0x80131537
  Message=Input string was not in a correct format.
  Source=mscorlib
  StackTrace:
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseInt32(String s, NumberStyles style, NumberFormatInfo info)
   at System.Convert.ToInt32(String value)
   at LogcatToolWin.AdbAgent.OutputHandler(Object sendingProcess, DataReceivedEventArgs outLine) in C:\prj\vsext\logcat\LogcatToolWin\AdbAgent.cs:line 267
   at System.Diagnostics.Process.OutputReadNotifyUser(String data)
  :`

source line is:
`int pid = System.Convert.ToInt32(pid_token);`

**Comment by robin88chen** [comment]
Fixed.
